services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: couchgpt-rag-chromadb
    ports:
      - "8002:8004"
    volumes:
      - ./docker-volumes/chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]

  rag-test:
    build:
      context: ./rag       # Adjust if your Dockerfile is elsewhere
      dockerfile: Dockerfile
    image: couchgpt-rag-cli
    container_name: rag-test
    depends_on:
      - chromadb
    ports:
      - "8088:9000"
    environment:
      - GCP_PROJECT=${GCP_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - CHROMADB_HOST=couchgpt-rag-chromadb
      - CHROMADB_PORT=8004
      - RAG_ENV=${RAG_ENV}
    env_file:
      - .env
    volumes:
      - ../secrets:/secrets:ro
      - ./rag:/app
    working_dir: /app
    entrypoint: ""
    command: ["pipenv", "run", "uvicorn", "rag:app", "--host", "0.0.0.0", "--port", "9000"]