services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: couchgpt-rag-chromadb
    ports:
      - "8002:8004"
    volumes:
      - ./docker-volumes/chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004"]
      interval: 10s
      timeout: 5s
      retries: 3

  rag-test:
    build:
      context: ./rag
      dockerfile: Dockerfile
    image: couchgpt-rag-cli
    container_name: rag-test
    depends_on:
      - chromadb
    ports:
      - "8088:9000"
    env_file:
      - .env
    volumes:
      - ./secrets:/secrets:ro
      - ./rag:/app
    working_dir: /app
