  rag-test:
    build:
      context: ./rag
      dockerfile: Dockerfile
    image: couchgpt-rag-cli
    container_name: rag-test
    depends_on:
      - chromadb
    ports:
      - "8088:9000"
    env_file:
      - .env
    volumes:
      - ../secrets:/secrets:ro
      - ./rag:/app
    working_dir: /app
    entrypoint: ""
    command: ["pipenv", "run", "uvicorn", "rag:app", "--host", "0.0.0.0", "--port", "9000"]
