name: RAG API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      RAG_ENV: ${{ secrets.RAG_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start containers
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Wait for app to fully start
        run: sleep 10

      - name: Show container logs if app crashes
        if: failure()
        run: docker logs rag-test

      - name: Run integration tests
        run: docker exec rag-test pipenv run pytest tests/ -v

      - name: Tear down containers
        if: always()
        run: docker-compose -f docker-compose.test.yml down
