name: RAG API Tests (No GCP Secrets)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and start containers
      run: docker-compose -f docker-compose.test.yml up -d --build

    - name: Run tests inside container with PYTHONPATH
      run: docker exec rag-test bash -c "export PYTHONPATH=/app && pipenv run pytest tests/"

    - name: Tear down containers
      if: always()
      run: docker-compose -f docker-compose.test.yml down
